### ISSUE TITLE
ExoPlayer

### ISSUE THREAD

**Issue by LutfiTekin** [LutfiTekin/RadyoMenemenPro#2]
Standart mediaplayer apisinden exoplayera geçiş

**Comment by AKSAKALLIDEDE** [comment]
Merakla bekliyiruz bakalım

**Comment by LutfiTekin** [comment]
@AKSAKALLIDEDE panpa çok fazla bişey değişmemiş gibi gelebilir onu söyliyim baştan

**Comment by LutfiTekin** [comment]
@AKSAKALLIDEDE buffer ollayı biraz farklıymış yalnız, akıştaki şarkı kaldığı yerden devam etmiyor akışa daha yakın gibi
