### ISSUE TITLE
Menemen Puan: Üyelerin Akışa Müdahalesi Sistemi

### ISSUE THREAD

**Issue by LutfiTekin** [LutfiTekin/RadyoMenemenPro#3]
Kullanıcılar şarkı dinlerken biriktirdikleri puanlar ile çalan şarkıyı değiştirebilme yetkisine sahip olabilecekler.
- Şarkı değiştirme başarılı olursa diğer dinleyenlere kimin şarkıyı değiştirdiği bilgisi gidecek
- Anonim olarak şarkı değiştirmek isteyenler 2 kat puan ile değiştirebilecek

**Comment by AKSAKALLIDEDE** [comment]
Çok güzel bir fikir ancak sıradaki şarkıyı görmeden değiştirmek ürünü görmeden para ödemek gibi bir şey olmaz mı?

**Comment by LutfiTekin** [comment]
Puanı sonraki şarkı için değil, o an çalan şarkıyı değiştirmek için vereceksin.
